version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:80"
    env_file:
      - .env
    environment:
      REDIS_URL: ${REDIS_URL:-}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-17911}
      REDIS_USERNAME: ${REDIS_USERNAME:-}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      REDIS_SCHEME: ${REDIS_SCHEME:-tcp}
      CACHE_DRIVER: ${CACHE_DRIVER:-redis}
      SESSION_DRIVER: ${SESSION_DRIVER:-redis}
      QUEUE_CONNECTION: ${QUEUE_CONNECTION:-redis}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "17911:17911"
